<?xml version="1.0" encoding="utf-8"?><Database Name="Student" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-0S794175;Initial Catalog=Student;Integrated Security=True" SettingsObjectName="ADO.NET_demo.Properties.Settings" SettingsPropertyName="StudentConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StudentDetalis" Member="StudentDetalis">
    <Type Name="StudentDetali">
      <Column Name="studentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>